feat(kubernetes): support env inject

diff --git a/kubernetes/Makefile b/kubernetes/Makefile
--- a/kubernetes/Makefile
+++ b/kubernetes/Makefile
@@ -1,80 +1,165 @@
+# Copyright 2019 The Caicloud Authors.
+#
+# The old school Makefile, following are required targets. The Makefile is written
+# to allow building multiple binaries. You are free to add more targets or change
+# existing implementations, as long as the semantics are preserved.
+#
+#   make              - default to 'build' target
+#   make lint         - code analysis
+#   make test         - run unit test (or plus integration test)
+#   make build        - alias to build-local target
+#   make build-local  - build local binary targets
+#   make build-linux  - build linux binary targets
+#   make container    - build containers
+#   $ docker login registry -u username -p xxxxx
+#   make push         - push containers
+#   make clean        - clean up targets
+#
+# Not included but recommended targets:
+#   make e2e-test
+#
+# The makefile is also responsible to populate project version information.
+#
 
-# Image URL to use all building/pushing image targets
-IMG ?= controller:latest
-# Produce CRDs that work back to Kubernetes 1.11 (no version conversion)
-CRD_OPTIONS ?= "crd:trivialVersions=true"
+#
+# Tweak the variables based on your project.
+#
 
-# Get the currently used golang install path (in GOPATH/bin, unless GOBIN is set)
-ifeq (,$(shell go env GOBIN))
-GOBIN=$(shell go env GOPATH)/bin
-else
-GOBIN=$(shell go env GOBIN)
-endif
+# This repo's root import path (under GOPATH).
+ROOT := github.com/pytorch/elastic/kubernetes
 
-all: manager
+# Target binaries. You can build multiple binaries for a single project.
+TARGETS := elastic-controller
 
-# Run tests
-test: generate fmt vet manifests
-	go test ./... -coverprofile cover.out
+# Container image prefix and suffix added to targets.
+# The final built images are:
+#   $[REGISTRY]/$[IMAGE_PREFIX]$[TARGET]$[IMAGE_SUFFIX]:$[VERSION]
+# $[REGISTRY] is an item from $[REGISTRIES], $[TARGET] is an item from $[TARGETS].
+IMAGE_PREFIX ?= $(strip )
+IMAGE_SUFFIX ?= $(strip )
 
-# Build manager binary
-manager: generate fmt vet
-	go build -o bin/manager main.go
+# Container registries.
+REGISTRY ?= cargo.dev.caicloud.xyz/release
 
-# Run against the configured Kubernetes cluster in ~/.kube/config
-run: generate fmt vet manifests
-	go run ./main.go
+# Container registry for base images.
+BASE_REGISTRY ?= cargo.caicloud.xyz/library
 
-# Install CRDs into a cluster
-install: manifests
-	kustomize build config/crd | kubectl apply -f -
+#
+# These variables should not need tweaking.
+#
 
-# Uninstall CRDs from a cluster
-uninstall: manifests
-	kustomize build config/crd | kubectl delete -f -
+# It's necessary to set this because some environments don't link sh -> bash.
+export SHELL := /bin/bash
 
-# Deploy controller in the configured Kubernetes cluster in ~/.kube/config
-deploy: manifests
-	cd config/manager && kustomize edit set image controller=${IMG}
-	kustomize build config/default | kubectl apply -f -
+# It's necessary to set the errexit flags for the bash shell.
+export SHELLOPTS := errexit
 
-# Generate manifests e.g. CRD, RBAC etc.
-manifests: controller-gen
-	$(CONTROLLER_GEN) $(CRD_OPTIONS) rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
+# Project main package location (can be multiple ones).
+CMD_DIR := ./cmd
 
-# Run go fmt against code
-fmt:
-	go fmt ./...
+# Project output directory.
+OUTPUT_DIR := ./bin
 
-# Run go vet against code
-vet:
-	go vet ./...
+# Build direcotory.
+BUILD_DIR := ./build
 
-# Generate code
-generate: controller-gen
-	$(CONTROLLER_GEN) object:headerFile=./hack/boilerplate.go.txt paths="./..."
+# Current version of the project.
+VERSION      ?= $(shell git describe --tags --always --dirty)
+GITREMOTE    ?= $(shell git remote get-url origin)
+GITCOMMIT    ?= $(shell git rev-parse HEAD)
+GITTREESTATE ?= $(if $(shell git status --porcelain),dirty,clean)
+BUILDDATE    ?= $(shell date -u +"%Y-%m-%dT%H:%M:%SZ")
+GOCOMMON     := $(shell if [ ! -f go.mod ]; then echo $(ROOT)/vendor/; fi)github.com/caicloud/go-common
 
-# Build the docker image
-docker-build: test
-	docker build . -t ${IMG}
+# Available cpus for compiling, please refer to https://github.com/caicloud/engineering/issues/8186#issuecomment-518656946 for more information.
+CPUS ?= $(shell /bin/bash hack/read_cpus_available.sh)
 
-# Push the docker image
-docker-push:
-	docker push ${IMG}
+# Track code version with Docker Label.
+DOCKER_LABELS ?= git-describe="$(shell date -u +v%Y%m%d)-$(shell git describe --tags --always --dirty)"
 
-# find or download controller-gen
-# download controller-gen if necessary
-controller-gen:
-ifeq (, $(shell which controller-gen))
-	@{ \
-	set -e ;\
-	CONTROLLER_GEN_TMP_DIR=$$(mktemp -d) ;\
-	cd $$CONTROLLER_GEN_TMP_DIR ;\
-	go mod init tmp ;\
-	go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.2.4 ;\
-	rm -rf $$CONTROLLER_GEN_TMP_DIR ;\
-	}
-CONTROLLER_GEN=$(GOBIN)/controller-gen
-else
-CONTROLLER_GEN=$(shell which controller-gen)
-endif
+# Golang standard bin directory.
+GOPATH ?= $(shell go env GOPATH)
+BIN_DIR := $(GOPATH)/bin
+GOLANGCI_LINT := $(BIN_DIR)/golangci-lint
+
+# Default golang flags used in build and test
+# -mod=vendor: force go to use the vendor files instead of using the `$GOPATH/pkg/mod`
+# -p: the number of programs that can be run in parallel
+# -count: run each test and benchmark 1 times. Set this flag to disable test cache
+export GOFLAGS ?= -mod=vendor -p=$(CPUS) -count=1
+
+#
+# Define all targets. At least the following commands are required:
+#
+
+# All targets.
+.PHONY: lint test build container push
+
+build: build-local
+
+# more info about `GOGC` env: https://github.com/golangci/golangci-lint#memory-usage-of-golangci-lint
+lint: $(GOLANGCI_LINT)
+	@$(GOLANGCI_LINT) run
+
+$(GOLANGCI_LINT):
+	curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(BIN_DIR) v1.23.6
+
+test:
+	@go test -race -coverprofile=coverage.out ./...
+	@go tool cover -func coverage.out | tail -n 1 | awk '{ print "Total coverage: " $$3 }'
+
+build-local:
+	@for target in $(TARGETS); do                                                      \
+	  go build -v -o $(OUTPUT_DIR)/$${target}                                          \
+	    -ldflags "-s -w -X $(GOCOMMON)/version.version=$(VERSION)                      \
+	      -X $(GOCOMMON)/version.gitRemote=$(GITREMOTE)                                \
+	      -X $(GOCOMMON)/version.gitCommit=$(GITCOMMIT)                                \
+	      -X $(GOCOMMON)/version.gitTreeState=$(GITTREESTATE)                          \
+	      -X $(GOCOMMON)/version.buildDate=$(BUILDDATE)"                               \
+	    $(CMD_DIR)/$${target};                                                         \
+	done
+
+build-linux:
+	@docker run --rm -it                                                               \
+	  -v $(PWD):/go/src/$(ROOT)                                                        \
+	  -w /go/src/$(ROOT)                                                               \
+	  -e GOOS=linux                                                                    \
+	  -e GOARCH=amd64                                                                  \
+	  -e GOPATH=/go                                                                    \
+	  -e GOFLAGS="$(GOFLAGS)"                                                          \
+	  -e SHELLOPTS="$(SHELLOPTS)"                                                      \
+	  $(BASE_REGISTRY)/golang:1.13-security                                            \
+	    /bin/bash -c 'for target in $(TARGETS); do                                     \
+	      go build -v -o $(OUTPUT_DIR)/$${target}                                      \
+	        -ldflags "-s -w -X $(GOCOMMON)/version.version=$(VERSION)                  \
+	          -X $(GOCOMMON)/version.gitRemote=$(GITREMOTE)                            \
+	          -X $(GOCOMMON)/version.gitCommit=$(GITCOMMIT)                            \
+	          -X $(GOCOMMON)/version.gitTreeState=$(GITTREESTATE)                      \
+	          -X $(GOCOMMON)/version.buildDate=$(BUILDDATE)"                           \
+	        $(CMD_DIR)/$${target};                                                     \
+	    done'
+
+container: build-linux
+	@for target in $(TARGETS); do                                                      \
+	  image=$(IMAGE_PREFIX)$${target}$(IMAGE_SUFFIX);                                  \
+	  docker build -t $(REGISTRY)/$${image}:$(VERSION)                                 \
+	    --label $(DOCKER_LABELS)                                                       \
+	    -f $(BUILD_DIR)/$${target}/Dockerfile .;                                       \
+	done
+
+push: container
+	@for target in $(TARGETS); do                                                      \
+	  image=$(IMAGE_PREFIX)$${target}$(IMAGE_SUFFIX);                                  \
+	  docker push $(REGISTRY)/$${image}:$(VERSION);                                    \
+	done
+
+update: push
+	imageName=$(IMAGE_PREFIX)elasticjob-controller$(IMAGE_SUFFIX);                       \
+	image=$(REGISTRY)/$${imageName}:$(VERSION);                                        \
+	kubectl -n kube-system patch deploy mlneuron-controller-controller-v1-0 -p         \
+	"{\"spec\":{\"template\":{\"spec\":{\"containers\":[{\"name\":\"c0\",              \
+	\"image\":\"$${image}\"}]}}}}";                                                    \
+
+.PHONY: clean
+clean:
+	@-rm -vrf ${OUTPUT_DIR}
